kurone-kito/setup.windows

README.md

Improved the document.

---

setup.files/02.boxstarter/boxstarter_tasks.ps1

Fixed a bug that path to VSCode has broken

---

setup.cmd
setup.files/02.boxstarter/boxstarter_tasks.ps1
setup.files/02.boxstarter/index.ps1
setup.files/index.ps1

- Implemented that Show Windows edition at the start.
- Fixed that Failed at the start because specified invalid execution policy.
- Removed a feature because its name was wrong.

Cumulative update

---

setup.files/02.boxstarter/boxstarter_tasks.ps1
test

- Removed some unused plugins for Vagrant.
- Fixed the crash problem the tasks for BoxStarter.

Cumulative bugfix

---

.editorconfig

Added the EditorConfig settings

---

.editorconfig
setup.files/02.boxstarter/boxstarter_tasks.ps1

- AutoHotKey
- AWS Commandline Interface
- Gpg4win
- iCloud
- Noto font
- OBS Studio
- OpenSSH
- Git LFS
- Improved the EditorConfig settings.
- And linted.

Added some apps.

---

setup.files/02.boxstarter/boxstarter_tasks.ps1
setup.files/index.ps1

🎵 Added the folders for VST plugins

---

setup.files/02.boxstarter/boxstarter_tasks.ps1

- VS2017
- Unity ➧ Unity Hub
- jq
- posh-git
- and some VSCode plugins

Added some packages

---

setup.files/02.boxstarter/boxstarter_tasks.ps1

nodejs -> nudist
jq (JSON can be processed with PowerShell)

Improved the bundle

---

setup.files/02.boxstarter/boxstarter_tasks.ps1

Added the some packages

---

setup.files/02.boxstarter/boxstarter_tasks.ps1

Added the mkcert

---

setup.files/02.boxstarter/boxstarter_tasks.ps1

- Added NodeJS v13 updates to a setup script and removed v8 LTS. (58973e4)
- Added the below package installation. (833bd24)

Organized the install packages

---

README.md
Vagrantfile
setup.files/02.boxstarter/boxstarter_tasks.ps1
test

Removed support to Windows 7 and 8(.0)

---

Vagrantfile
setup.files/01.pre-setup/_boxstarter.ps1
setup.files/01.pre-setup/_chocolatey.ps1
setup.files/01.pre-setup/_virtualbox.ps1
setup.files/02.boxstarter/boxstarter_tasks.ps1
test

Cumulative updates

---

setup.files/02.boxstarter/boxstarter_tasks.ps1

Removed some packages

---

test

brewのコマンド修正パッチ

---

README.md
boxstarter.min.ps1
boxstarter.ps1
libs/.lib.psm1
libs/additional-setup.ps1
libs/choco-with-interactive.ps1
libs/docker.ps1
libs/edgeTweaks.ps1
libs/mkcert.ps1
libs/pre-setup.ps1
libs/unity.ps1

- added, and organized order of some apps installation (267860b)
- [Scoop](https://scoop.sh) (directly install)
- suppressed the extra warning messages (859bdd9)
- refactored that combines the paths (c0b33d1)
- improved the path resolve (c2c74cb)

cumulative updates, including additional apps to install and bug fixes

---

.vscode/settings.json

improved the VSCode configurations

---

boxstarter.min.ps1
boxstarter.ps1

feat: added the Node.js v19 installation

---

.vscode/settings.json
README.md
boxstarter.min.ps1
boxstarter.ps1

- added an app installation
- [FortiClient VPN](https://www.fortinet.com/products/endpoint-security/forticlient) (59afc98)
- Degraded the version of Yarn to be installed to v1. (f6785e0)
- If you are using Yarn 1.18.0 or later, it will automatically recognize the version designation and use the specified version.

Cumulative updates include that adds some app installation

---

README.md
libs/.lib.psm1
libs/docker.ps1
libs/unity.ps1

- 35dd4b0: added the installation that Unity Editor 2022
- bc7d12a: added the installation that Docker images
- c9c1334: fixed a crash bug in the function to confirm continuation
- 73913aa: improved the README

Cumulative updates include installation of the Unity Editor 2022 and bug fixes
